services:
  - type: web
    name: mcp-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python cloud_server.py
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
